<?php

/**
 * Registers a shortcode to render a frontend taxonomy filter dropdown.
 * 
 * Usage: [gb_tax_filter taxonomy="category" param="cat_filter"]
 *
 * @param array $atts The user-defined shortcode attributes.
 * @return string The HTML form for the taxonomy dropdown.
 */
add_shortcode( 'gb_tax_filter', function( $atts ) {
    // Extract and sanitize shortcode attributes, defining defaults.
    $args = shortcode_atts( array(
        'taxonomy' => 'category', // The registered taxonomy slug
        'param'    => 'tax_filter', // The URL GET parameter to use
    ), $atts );

    // Retrieve all non-empty terms for the specified taxonomy.
    $terms = get_terms( array(
        'taxonomy'   => sanitize_key( $args['taxonomy'] ),
        'hide_empty' => true,
    ) );

    // Return empty if no terms are found or an error occurs.
    if ( is_wp_error( $terms ) || empty( $terms ) ) {
        return '';
    }

    // Determine the currently selected term from the URL parameter, if any.
    $current_selection = isset( $_GET[ $args['param'] ] ) ? sanitize_text_field( wp_unslash( $_GET[ $args['param'] ] ) ) : '';

    // Begin output buffering to construct the HTML form securely.
    ob_start();
    ?>
    <form method="GET" action="<?php echo esc_url( get_permalink() ); ?>" class="gb-custom-tax-filter">
        <select name="<?php echo esc_attr( $args['param'] ); ?>" onchange="this.form.submit()">
            <option value=""><?php esc_html_e( 'All Options', 'generatepress' ); ?></option>
            <?php foreach ( $terms as $term ) : ?>
                <option value="<?php echo esc_attr( $term->slug ); ?>" <?php selected( $current_selection, $term->slug ); ?>>
                    <?php echo esc_html( $term->name ); ?>
                </option>
            <?php endforeach; ?>
        </select>
        
        <!-- Preserve existing query string parameters (like pagination) except the current filter -->
        <?php
        foreach ( $_GET as $key => $val ) {
            if ( $key !== $args['param'] && $key !== 'paged' ) {
                echo '<input type="hidden" name="' . esc_attr( sanitize_key( $key ) ) . '" value="' . esc_attr( sanitize_text_field( wp_unslash( $val ) ) ) . '" />';
            }
        }
        ?>
    </form>
    <?php
    
    // Return the buffered content.
    return ob_get_clean();
} );


/**
 * Intercepts GenerateBlocks Query Loop arguments to apply frontend taxonomy filtering.
 *
 * This function checks if a specific CSS class is applied to the Query Loop block,
 * and if the URL contains the designated filter parameter, it injects a tax_query.
 *
 * @param array $query_args The WP_Query arguments generated by GenerateBlocks.
 * @param array $attributes The block attributes of the current Query Loop block.
 * @return array The modified WP_Query arguments.
 */
add_filter( 'generateblocks_query_loop_args', function( $query_args, $attributes ) {
    
    // 1. Verify if this specific Query Loop block is the one we want to target.
    // We do this by checking for a custom CSS class 'filtered-query-loop' added in the block settings.
    if ( ! empty( $attributes['className'] ) && strpos( $attributes['className'], 'filtered-query-loop' ) !== false ) {
        
        // 2. Define the URL parameter and taxonomy to listen for.
        // These should match the attributes used in your shortcode.
        $param    = 'tax_filter';
        $taxonomy = 'category'; // Change this if you are using a custom taxonomy (e.g., 'product_cat')

        // 3. Check if the parameter exists in the URL and isn't empty.
        if ( ! empty( $_GET[ $param ] ) ) {
            $term_slug = sanitize_text_field( wp_unslash( $_GET[ $param ] ) );

            // 4. Initialize the tax_query array if GenerateBlocks hasn't already created it.
            if ( ! isset( $query_args['tax_query'] ) ) {
                $query_args['tax_query'] = array();
            }

            // 5. Inject our custom taxonomy requirement into the query arguments.
            $query_args['tax_query'][] = array(
                'taxonomy' => $taxonomy,
                'field'    => 'slug',
                'terms'    => $term_slug,
            );
        }
    }

    // Return the modified or unmodified query arguments.
    return $query_args;
}, 10, 2 );